name: Flutter CI

on:
  push:
    tags:
      - v*
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - uses: subosito/flutter-action@v2.1.0
        with:
          channel: 'stable'
      - run: flutter packages get
      - run: flutter build apk --release
      - run: ls
      - run: mv build/app/outputs/flutter-apk/app-release.apk intro/app-release.apk
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          path: intro/app-release.apk
